# This GitHub Actions workflow is named "hello world workflow".
# It is triggered by the following events:
# - A push to the "main" branch.
# - A pull request targeting the "main" branch.
# - A manual trigger via the "workflow_dispatch" event.
#
# The workflow defines two jobs:
# 1. "hello":
#    - Runs on the latest Ubuntu environment.
#    - Checks out the repository code using the "actions/checkout@v2" action.
#    - Executes a script that prints "Hello, world!" to the console using the Bash shell.
#
# 2. "goodbye":
#    - Runs on the latest Ubuntu environment.
#    - Checks out the repository code using the "actions/checkout@v2" action.
#    - Executes a script that prints "Goodbye, world!" to the console using the Bash shell.
name: hello world workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main  
  workflow_dispatch:
jobs: 
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run hello world script
        run: echo "Hello, world!"
        shell: bash

  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run goodbye world script
        run: echo "Goodbye, world!" 
        shell: bash