name: hello world workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main  
  workflow_dispatch:
jobs: 
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v2

      - name: Run hello world script
        run: echo "Hello, world!"
        shell: bash
  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v2

      - name: Run goodbye world script
        run: echo "Goodbye, world!" 
        shell: bash